################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
MQTTConnectClient.obj: C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src/MQTTConnectClient.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="MQTTConnectClient.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

MQTTConnectServer.obj: C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src/MQTTConnectServer.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="MQTTConnectServer.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

MQTTDeserializePublish.obj: C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src/MQTTDeserializePublish.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="MQTTDeserializePublish.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

MQTTPacket.obj: C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src/MQTTPacket.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="MQTTPacket.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

MQTTSerializePublish.obj: C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src/MQTTSerializePublish.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="MQTTSerializePublish.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

MQTTSubscribeClient.obj: C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src/MQTTSubscribeClient.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="MQTTSubscribeClient.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

MQTTSubscribeServer.obj: C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src/MQTTSubscribeServer.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="MQTTSubscribeServer.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

MQTTUnsubscribeClient.obj: C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src/MQTTUnsubscribeClient.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="MQTTUnsubscribeClient.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

MQTTUnsubscribeServer.obj: C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src/MQTTUnsubscribeServer.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="MQTTUnsubscribeServer.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

adc_func.obj: C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib/adc_func.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="adc_func.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

gpio_if.obj: C:/ti/CC3200SDK/cc3200-sdk/example/common/gpio_if.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="gpio_if.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

i2c_if.obj: C:/ti/CC3200SDK/cc3200-sdk/example/common/i2c_if.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="i2c_if.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

main.obj: C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/main.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="main.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

network_if.obj: C:/ti/CC3200SDK/cc3200-sdk/example/common/network_if.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="network_if.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

pinmux.obj: C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/pinmux.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="pinmux.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

timer_if.obj: C:/ti/CC3200SDK/cc3200-sdk/example/common/timer_if.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="timer_if.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

tmp006drv.obj: C:/ti/CC3200SDK/cc3200-sdk/example/out_of_box/tmp006drv.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="tmp006drv.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

uart_if.obj: C:/ti/CC3200SDK/cc3200-sdk/example/common/uart_if.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="uart_if.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

wdt_if.obj: C:/ti/CC3200SDK/cc3200-sdk/example/common/wdt_if.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"c:/ti/ccsv6/tools/compiler/arm_5.1.5/bin/armcl" -mv7M4 --code_state=16 --abi=eabi -me -Ooff --opt_for_speed=0 --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/MQTTPacket/src" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/watchdog" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/adc_lib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/adc" --include_path="c:/ti/ccsv6/tools/compiler/arm_5.1.5/include" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/aes" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email" --include_path="C:/ti/CC3200SDK/cc3200-sdk/example/common" --include_path="C:/ti/CC3200SDK/cc3200-sdk/oslib" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/source" --include_path="C:/ti/CC3200SDK/cc3200-sdk/simplelink/include" --include_path="C:/ti/CC3200SDK/cc3200-sdk/inc" --include_path="C:/Users/pkrza/GIT/execom_praksa/execom-praksa/email/Includes/driverlib" -g --define=SL_PLATFORM_MULTI_THREADED --define=USE_TIRTOS --define=__CCS__ --define=ccs --define=cc3200 --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="wdt_if.pp" --cmd_file="C:/ti/CC3200SDK/cc3200-sdk/ti_rtos/ti_rtos_config/Default/configPkg/compiler.opt" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


